In [1]:
import numpy as np
import matplotlib.pyplot as plt
from quantecon import LQ
from collections import namedtuple
from DynLinEcon import DLE
from math import sqrt
%matplotlib inline

In [14]:
# Parameters: deltah, thetah, llambda, beta and pih are from Tom's exam question.
# The rest of the parameters are from the Hall (1978) model of Chapter 5. (Only ub is relevant for this)

gamma1 = 0.1
gamma = np.array([[gamma1],[0]])
phic = np.array([[1],[0]])
phig = np.array([[0],[1]])
phi1 = 0.00001
phii = np.array([[1],[-phi1]])
deltak = np.array([[.95]])
thetak = np.array([[1]])

a22 = np.array([[1,0,0],[0,0.8,0],[0,0,0.5]])
c2 = np.array([[0,0],[1,0],[0,1]])
ud = np.array([[5,1,0],[0,0,0]])
ub = np.array([[30,0,0],[0,0,0]])
x0 = np.array([[5],[150],[1],[0],[0]])

deltah1 = 0.9
deltah = np.array([[0,1,1,0,0],[0,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[1-deltah1,0,0,0,deltah1]])
thetah = np.array([[1],[1],[0],[0],[0]])
lam1=1
llambda = np.array([[lam1, 0, 0, 0, 0],[0,0,0,0,-lam1]])
beta = np.array([[0.95]])
pih = np.array([[0],[0]])

Info1 = (a22,c2,ub,ud)
Tech1 = (phic,phig,phii,gamma,deltak,thetak)
Pref1 = (beta,llambda,pih,deltah,thetah)

In [15]:
Econ1 = DLE(Info1, Tech1, Pref1)

In [16]:
Econ1.canonical()

In [17]:
Econ1.pihat

array([[ 0.99247256]])

In [18]:
Econ1.llambdahat

array([[ 0.03174053,  0.99247256,  0.99247256,  0.        ,  0.28566479]])

In [19]:
Econ1.ubhat

array([[ 23.74153667,  -0.        ,  -0.        ]])